### ISSUE TITLE
Imperatively update cache contents outside of Query/Mutation workflow

### ISSUE THREAD

**Issue by lukasluecke** [FormidableLabs/urql-exchange-graphcache#109]
I have a WebSocket subscription (not GraphQL) and would like to update parts of cached GraphQL queries in response to messages I receive there. Is there a clean way to achieve this?

**Comment by JoviDeCroock** [comment]
Yes similar to how you declare update.Mutation you can declare update.Subscription like here: https://github.com/JoviDeCroock/threed-web/blob/master/src/index.js#L141

**Comment by lukasluecke** [comment]
It's not a GraphQL subscription - it's some asynchronous process running "outside" of the whole urql / GraphQL stuff.

**Comment by lukasluecke** [comment]
I would probably need something like `useCache` similar to `useClient`, that gives me access to `writeFragment` etc.

**Comment by JoviDeCroock** [comment]
A client process that alters your data on the server but is not reflected from there?

**Comment by lukasluecke** [comment]
The data is already updated on the server, but we can't use GraphQL subscriptions for that right now due to technical/architecture reasons (hopefully not much longer 🙈).

I want something like an optimistic update triggered manually, until the next refetch from server (which will have the same / updated data).

**Comment by lukasluecke** [comment]
The WebSocket (or SSE, or anything else) connection is more like a second communication channel, that can trigger refreshes of data. Since these messages already include some / all of the data I want to refresh, I'd like to directly write it to the cache instead of refetching the related queries (which works fine already).

**Comment by kitten** [comment]
This is a conscious constraint we’ve actually added. If you look at the store itself (which we often refer to as the cache instance) it explicitly has some guards that disallow it being accessed outside of operations.

This is a constraint that allows us to make a lot of assumptions about updates and data changes, especially in the presence of schema information.

It is simply not safe to mutate the cache outside of operations, where an outcome is unpredictable. We see the cache and its config as one reactive unit that only deals with GraphQL responses and adheres to the API’s intent and schema.

An alternative though could be for you to return artificial subscription responses as an exchange and react to those. You could also think about integrating your non-GraphQL subscriptions into urql.

Admittedly there would be some work involved, but you’d properly bring your WS connection into GraphQL, so to speak.

But the quickest solution may be to deliver your events in an exchange as “faux” responses and to react to those subscription results using Graphcache updates.

**Comment by lukasluecke** [comment]
Thanks for the detailed response @kitten (and also @JoviDeCroock for your fast replies earlier!)

My goal long term is to move towards "plain" GraphQL subscriptions anyway (with a custom transport or something), but until then, I'd like to try the "quick solution".

Any pointers on what exactly you're suggesting? How would I provide "faux" responses to an exchange?

**Comment by kitten** [comment]
Ok, I think we've accidentally dropped the ball here! Sorry 😓 

What we mean by "faux responses" is that you can write an exchange that sends results without having any operations come in. You'd basically have an exchange after Graphcache that sends results that correspond to your out-of-GraphQL results. That's obviously not the best solution, but its constraints would help Graphcache retain its cache integrity.
