### ISSUE TITLE
Implement benchmark comparing our operations to apollo-cache-inmemory

### ISSUE THREAD

**Issue by kitten** [FormidableLabs/urql-exchange-graphcache#45]
We need some kind of reference point and performance budget to be able to estimate the impact of upcoming changes, especially before we address #4 

Some simple `write` and `query` benchmarks where we write bulk data and read it back would do the trick. Such a data sample should at least:

- contain 10,000+ entities
- 5 different types with 5 fields each
- nested lists of a depth of at least 3

**Comment by JoviDeCroock** [comment]
Resolved by: #46
