### ISSUE TITLE
Package name prefixing

### ISSUE THREAD

**Issue by andyrichardson** [FormidableLabs/urql-exchange-graphcache#6]
For consistencies sake, lets exclude the `exchange` prefix ([devtools](https://www.npmjs.com/package/@urql/devtools) is just `@urql/devtools`).

Most libraries are going to be an exchange anyway so the prefix doesn't add much value.

**Comment by kitten** [comment]
For now, both `@urql/exchange-suspense` and `@urql/exchange-graphcache` follow the naming convention of `@urql/` + `exchange` + name/topic. This is very much inspired by Babel's naming convention.

I don't expect the devtools exchange to necessarily follow that, but I do think it provides clarity above any other actual meaningful value. Let's hold off on making any more conventions than the two though. I think all three of these are valid naming conventions:

- name a package `@urql/exchange-*` or `@urql/*`
- name a (third-party package) `urql-exchange-*` or `urql-*`
- name repos `urql-exchange-*` or `urql-*`
