### ISSUE TITLE
Passing introspection schema breaks the client

### ISSUE THREAD

**Issue by jBugman** [FormidableLabs/urql-exchange-graphcache#64]
Client breaks with ```Uncaught (in promise) Invariant Violation: Invalid type: The type `undefined` is not an object in the defined schema, but the GraphQL document is traversing it```

Reproducible with the simplest schema
```
type Post {
  id: Int!
  author: String!
}

type Query {
  post(id: Int!): Post!
}
```
Cache is set up like that
```
exchanges: [
      dedupExchange,
      cacheExchange({
        schema: introspectionSchema, // see console.log below
      }),
      fetchExchange,
    ],
```
`introspectionSchema` looks like that:
<img width="378" alt="image" src="https://user-images.githubusercontent.com/891785/64455927-95309780-d0f7-11e9-8cf4-afc2b125cd74.png">

**Comment by kitten** [comment]
@jBugman hiya, that's one of our warnings/invariants that validates queries. Obviously sth has gone wrong with it. I've just checked its source and I may have an idea of what's going on.

Can you wend me the query that you tried to run please?

**Comment by jBugman** [comment]
@kitten, thanks for the fast reply!

Minimal reproducing query (I removed almost all fields) is
```
query getPostsQuery {
  posts {
    id
  }
}
```
defined as
```
type Query {
  posts: [Post!]!
}
```
But it actually breaks on every our query I tried.

**Comment by kitten** [comment]
to narrow this down, does this happen with RC.3? If it isn't happening in RC.1 then it's probably related to some flawed validation stuff

**Comment by jBugman** [comment]
Yes, this reproduces in both rc.3 and rc.2 but works with rc.1 as far as I can see. I started playing with `graphcache` today, so I initially only tried on `@latest`

**Comment by kitten** [comment]
Aha, that makes sense. it's probably related to https://github.com/FormidableLabs/urql-exchange-graphcache/pull/63 😅  I'll see whether I'll find the time to fix it this eve or next week :+1:

**Comment by jBugman** [comment]
I can provide stacktrace only from bundled/minified version at the moment, which, I think may not be very helpful.
```
 at browser
    at expectObjectType
    at getField
    at SchemaPredicates.isFieldAvailableOnType
    at writeSelection
    at startWrite
    at write
    at updateCacheWithResult
```
(I removed useless source locations)

**Comment by JoviDeCroock** [comment]
Hey @jBugman 

Thanks for the reproduction, it helped us solve the issue much quicker. The new release `1.0.0-rc.4` (current latest) has the fix.

**Comment by switz** [comment]
Hmm, I'm not seeing an error thrown, but no data is returned once I pass in my schema. I'm on the latest version & using `react-native` (which may have an effect).

The API is definitely returning the data as seen below. But the last line still has `data: {}` returned from my `useQuery`.

Here's my schema.json: https://gist.github.com/switz/b22aed2da80dc1c58e696ea827f21cb4

<img width="1306" alt="Screen Shot 2019-09-17 at 4 46 59 AM" src="https://user-images.githubusercontent.com/990166/65063365-1683f780-d94c-11e9-90f8-61c8a4af886a.png">
