### ISSUE TITLE
Returning `null` from `KeyGenerator` messes up the data in array query

### ISSUE THREAD

**Issue by jBugman** [FormidableLabs/urql-exchange-graphcache#67]
Synthetic example schema
```
type Child {
  value: String!
}

type Parent {
  id: ID!
  child: Child!
}

type Query {
  getParents: [Parent!]
}
```
My intention is to all Children to always be embedded in the Parents. By default it works that way (at least is looks like that) but I get warnings `... Entities without keys will be embedded directly on the parent entity. If this is intentional, create a `keys` config for `PostTextContent` that always returns null.`
If I do that warning suggests and add this to config
```
cacheExchange({
  keys: {
    Child: () => null,
  }
})
```
then query data becomes overwritten.

Real network request data
```
{
    "getParents": [
        {
            "id": 1,
            "child": {
                "value": "AAA"
            }
        },
        {
            "id": 2,
            "child": {
                "value": "BBB"
            }
        },
        {
            "id": 3,
            "child": {
                "value": "CCC"
            }
        }
    ]
}
```
while data returned from `useQuery` to the component becomes
```
{
    "getParents": [
        {
            "id": 1,
            "child": {
                "value": "CCC"
            }
        },
        {
            "id": 2,
            "child": {
                "value": "CCC"
            }
        },
        {
            "id": 3,
            "child": {
                "value": "CCC"
            }
        }
    ]
}
```

**Comment by kitten** [comment]
oh dear, that's another bug I've introduced. Hold on, I'll push a fix 😅

**Comment by jBugman** [comment]
Wow that was fast

**Comment by kitten** [comment]
RC.5 includes this patch :+1: https://github.com/FormidableLabs/urql-exchange-graphcache/commit/9eeafa4796ed7d260a624cef1c3ac720592df6b9
