### ISSUE TITLE
Dynamic key generation / ignore Relay pagination helpers

### ISSUE THREAD

**Issue by lukasluecke** [FormidableLabs/urql-exchange-graphcache#74]
Using a Relay-based (following their spec) API with pagination results in lots of warnings, because all the `Connection` and `Edge` objects do not have an `id`. Maybe we could add a way to dynamically generate keys with a function that get's passed the `Type`, or just add an option to ignore all these pagination helper types?

**Comment by kitten** [comment]
A `relayPagination` helper is now very close to be merged :tada: https://github.com/FormidableLabs/urql-exchange-graphcache/pull/91
